version: '3.4'

services:
  mamumi:
    image: mamumi
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - mamumi
    depends_on:
      - mariadb
    command: ["npm", "run", "start-debug"]

  mariadb:
    container_name: mamumi_mariadb
    image: mariadb:5.5
    restart: unless-stopped
    volumes:
      - mariadb-volume:/var/lib/mysql
      - mariadb-logs-volume:/logs/db
    ports:
      - '3306:3306'
    networks:
      - mamumi
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  
volumes:
  mariadb-volume:
  mariadb-logs-volume:

networks:
  mamumi:
    driver: bridge
