version: '3.4'

services:
  mamumi:
    image: mamumi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - mamumi-audio:/mamumi/static/audio
    ports:
      - 3000:3000
    networks:
      - mamumi

  mariadb:
    container_name: mamumi_mariadb
    image: mariadb:5.5
    restart: unless-stopped
    volumes:
      - mariadb-volume:/var/lib/mysql
      - mariadb-logs-volume:/logs/db
    ports:
      - '3306:3306'
    networks:
      - mamumi
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  phpmyadmin:
    container_name: 'mamumi_phpmyadmin'
    image: 'phpmyadmin'
    ports:
        - '8080:80'
    networks:
        - mamumi
    environment:
        - PMA_HOST=mariadb
  
volumes:
  mariadb-volume:
  mariadb-logs-volume:
  mamumi-audio:

networks:
  mamumi:
    driver: bridge