version: '3.4'

services:
  mamumi:
    image: mamumi-dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: ["npm", "run", "start.dev"]
