version: '3.4'

services:
  mamumi:
    image: mamumi-debug
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:3000
      - 9229:9229
    networks:
      - mamumi
    command: ["npm", "run", --inspect=0.0.0.0:9229", "start"]

  mariadb:
    container_name: mamumi_mariadb-debug
    image: mariadb:5.5
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
      - mariadb-logs-volume:/logs/db
    ports:
      - '3306:3306'
    networks:
      - mamumi
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  phpmyadmin:
    container_name: 'mamumi_phpmyadmin-debug'
    image: 'phpmyadmin'
    ports:
        - '8080:80'
    networks:
        - mamumi
    environment:
        - PMA_HOST=mariadb
  
volumes:
  mariadb-volume:
  mariadb-logs-volume:

networks:
  mamumi:
    driver: bridge
