version: '3.4'

services:
  mamumi:
    image: mamumi
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/mamumi
      - /mamumi/node_modules
    ports:
      - 3000:3000
      - 9229:9229
      - 9230:9230
    command: ["npm", "run", "start-debug"]
