version: '3.4'

services:
  mamumi:
    image: mamumi-debug
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: ["npm", "run", --inspect=0.0.0.0:9229", "start"]
