version: '3.4'

services:
  mamumi:
    image: mamumi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - mamumi-audio:/mamumi/static/audio
    ports:
      - 3000:3000

volumes:
  mamumi-audio: